id: I4DDD7A3A
legacy_id: P002995
ocr_import_info:
  bdrc_scan_id: W1KG12987
  source: bdrc
  ocr_info:
    timestamp: '2020-03-23T00:39:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T04:32:19.150192+00:00'
last_modified: 2022-08-27 12:32:58.204856
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG12987
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG12987
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་རིན་ཆེན་ཕྲེང་བའི་རྩ་བ་དང་འགྲེལ་པ།
  author: སློབ་དཔོན་ཀླུ་སྒྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.9500796416364599
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG13064:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13064
      total_pages: 442
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13064.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9500796416364599
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
